import Header from "@/components/partials/Header";
import "./globals.css";

export const metadata = {
  title: "Kira Next",
  description: "Generated by Kira Next",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
